JSON input support
programmfabrik/gotmplx pull request #3
Opened 2021-09-03 10:45 UTC by leonsteinhaeuser

This PR adds the following functionalities:
* json input from file
* json input from stdin
  * see: `echo "{\"sample\": \"world\"}" | ./gotmplx --json key=- --eval "sample: {{ .JSON.key.sample }}"`

**Precondition:**
* json files must start with `{` and end with `}`.

2021-09-03 11:39 UTC, martinrode requested changes

2021-09-03 11:39 UTC, martinrode commented on main.go
> +		if jsonFileName == "-" {
*   Make sure to only have one value using "-"
*   Check for double keys, error out

2021-09-03 13:04 UTC, unai-programmfabrik reviewed
Seems fine.
As @martinrode says, careful with the stdin, either you cache the bytes and user in whatever keys and allow duplicates, or throw an error if any key is duplicated (or only '-')
You could also support inline JSON, like `--json key='{"whatever":{"is":["here","there"]}}'`

2022-08-15 09:35 UTC, martinrode commented
Outdated

2022-08-15 09:35 UTC, closed without merging